### ISSUE TITLE
Format file results in incorrect location for output files

### ISSUE THREAD

**Issue by shnhrrsn** [artemnovichkov/Carting#27] opened 2018-10-27 12:35 UTC
When running `carting update -f file` the frameworks are correctly individually added to 'input files', however rather than being added to 'output files' they're being added to 'output file lists'

**Comment by artemnovichkov** [comment] 2018-10-29 03:08
Hi, @shnhrrsn! Thanks for the issue! Is it a duplicate of #23? can I close this one?

**Closed as completed** 2018-10-29 07:17 UTC
